# Generated by Django 3.1.3 on 2020-12-27 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_bid_categorie_comment_listing_watchlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='start_at',
            field=models.DateTimeField(),
        ),
    ]
