# Generated by Django 3.1.3 on 2021-01-01 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0007_auto_20201231_1813'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bid',
            name='winner',
            field=models.BooleanField(default=False),
        ),
    ]
